version: "3.8"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
